# Generated by Django 3.0.4 on 2020-03-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apply_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('major', models.CharField(blank=True, max_length=20)),
                ('grade', models.IntegerField(blank=True)),
                ('grade_num', models.CharField(blank=True, max_length=20)),
                ('motivation', models.TextField()),
                ('webservice', models.TextField()),
                ('getting', models.TextField()),
            ],
        ),
    ]
