# Generated by Django 3.0.4 on 2020-03-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_supply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_user',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='apply_user',
            name='getting',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='apply_user',
            name='motivation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='apply_user',
            name='webservice',
            field=models.TextField(blank=True),
        ),
    ]
